[profile.default]
solc = '0.8.17'
optimizer_runs = 1_000_000
src = 'src'
out = 'out'
libs = ['lib']
bytecode_hash = "none"

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true

[rpc_endpoints]
mainnet = '${ETH_RPC_URL}'
goerli = '${GOERLI_RPC_URL}'
polygon = '${POLYGON_RPC_URL}'
polygon_mumbai = '${MUMBAI_RPC_URL}'

# See more config options https://github.com/foundry-rs/foundry/tree/master/config